### ISSUE TITLE
这个可以在正式环境手机日志吗？

### ISSUE THREAD

**Issue by AciGo** [wutiange/log-record#3]
我看配置只能在同一局域网才可以收集和查看日志，线上的可以继承和收集吗？

**Comment by wutiange** [comment]
你集成插件 https://github.com/wutiange/log-listener-plugin 插件后，有一个setBaseUrl 的 API，如果你在正式环境也设置了这个值，那么正式环境也可以拿到日志，但是这个客户端是部署到本地的；所以正式环境即便可以收集，你也需要让对应的手机和这个客户端处于同一个局域网内才能看到日志。

我这个日志系统主要解决的是测试工程师测试过程中出现问题，然后不知道是谁的问题，又不好复现，但是如果有这个日志系统收集日志，开发人员就可以直接查看对应的日志，看看是啥情况；同时可以收集接口请求的日志，这样测试工程师就不用开代理直接就能抓取app的网络日志，也非常方便的看看是app渲染的问题，还是接口返回的数据有问题。

我觉得更重要的还是跟蓝牙相关的日志。因为抓蓝牙的包是很困难的，而且抓到蓝牙的包也是不方便查看的，通过这个系统就可以解决这个问题，当然前提是你得在app中打对应的日志，不然日志系统也不会输出。

根据你的描述我觉得你可能是想看线上的日志，线上的日志我更推荐使用sentry来收集，然后在sentry上查看对应的日志。

**Comment by AciGo** [comment]
@wutiange 好的 了解了 非常感谢你的回答
