### ISSUE TITLE
新版本引入报错

### ISSUE THREAD

**Issue by ziwen-wang** [wutiange/log-record#4]
// // log 接管
import '@wutiange/log-listener-plugin/dist/console';
// // fetch 的接管
// import '@wutiange/log-listener-plugin/dist/fetch';
引入直接页面打不开
2.0.1版本 我这边报错

**Comment by ziwen-wang** [comment]
![1732452647504](https://github.com/user-attachments/assets/4ba52505-056c-4db2-b171-bae0580c2917)
是否大小写问题

**Comment by wutiange** [comment]
> // // log 接管 import '@wutiange/log-listener-plugin/dist/console'; // // fetch 的接管 // import '@wutiange/log-listener-plugin/dist/fetch'; 引入直接页面打不开 2.0.1版本 我这边报错

最新版本，大于等于v2.0.1的版本已经废弃这个导入方式

**Comment by wutiange** [comment]
> ![1732452647504](https://private-user-images.githubusercontent.com/19220127/389273631-4ba52505-056c-4db2-b171-bae0580c2917.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTk2NTksIm5iZiI6MTczMjQ1OTM1OSwicGF0aCI6Ii8xOTIyMDEyNy8zODkyNzM2MzEtNGJhNTI1MDUtMDU2Yy00ZGIyLWIxNzEtYmFlMDU4MGMyOTE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE0NDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWMyYmU1MDhjN2NkODIzMDExZDVjN2EwMGMwMzFkOWNiNmVhZmM1YTU5NjhjM2FiYjY3MzZmNTJiNmNkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GMWSWPxLF_44hcR08gklD0-2icpOryd7apcrxeiD-FA) 是否大小写问题

已经在[2.0.2-alpha.1](https://www.npmjs.com/package/@wutiange/log-listener-plugin/v/2.0.2-alpha.1)中修复
